site_name: Locating Facilities Doc

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false  
      custom_templates: templates
      watch:
        - app

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - docs/javascripts/maths.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js