site_name: Locating Facilities Documentation

theme:
  name: "material"

nav:
  - Home: index.md
  - Api Reference:
    - models: api/models.md
    - gui: api/gui.md
    - controller: api/controller.md
    - utils: api/utils.md

repo_url: https://github.com/dcordb/locating-facilities

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters: ['!^_', '^__init__$']
          rendering:
            show_source: true
            show_if_no_docstring: true
            show_object_full_path: false
            show_root_toc_entry: true
            show_root_full_path: false
            group_by_category: false
            show_category_heading: false
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules['Shiboken'] = mock()
      watch:
        - app

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include

extra_javascript:
  - docs/javascripts/maths.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js